[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "nss", "nspr", "atk", "cups", "dbus", "libdrm", "mesa", "xorg.libxkbcommon"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"
