[phases.setup]
nixPkgs = ["nodejs_18" "chromium"]

[phases.install]
cmds = [
  "npm install --omit=dev",
  "export CHROMIUM_PATH=$(which chromium || which chromium-browser || which google-chrome || true)"
]

[start]
cmd = "node server.js"
