[phases.setup]
nixPkgs = [
  "nodejs_18"
  "chromium"   # نثبت Chromium من البداية
]

[phases.install]
cmds = [
  # تثبيت الحزم بسرعة من package-lock
  "npm ci --omit=dev",

  # تحديد مسار Chromium المثبت مسبقًا لاستخدامه في puppeteer-core
  "export CHROMIUM_PATH=$(which chromium || which chromium-browser || which google-chrome || true)"
]

[start]
cmd = "node server.js"
